name: Tests
on: 
  repository_dispatch:
    types: [tests-report]
  push:
  pull_request_target:
    types: [opened, edited]
jobs:
  tests:
    strategy:
      matrix:
        platform: [ubuntu-latest]  # mac-os in development
    runs-on: ${{ matrix.platform }}
    env:
      RUST_BACKTRACE: 1
    steps:
      - name: Checkout branch
        uses: actions/checkout@v2
      - name: Install Node
        uses: actions/setup-node@v2
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable-2020-10-08
          target: wasm32-unknown-unknown
      - name: Run unit tests
        run: cd ft && cargo test -- --nocapture --color=always
      - name: Run Rust integration tests
        run: cd integration-tests/rs && cargo run --example integration-tests
      - name: Run TS integration tests 
        run: cd integration-tests/ts && yarn && yarn test
